import type { Metadata } from "next";
import "./globals.css";
// import Image from 'next/image'

// 로고 사용
// import Logo from "/public/assets/logo.png";

// 단일 font 사용
// import { Roboto } from 'next/font/google'

// 다중 font 사용
import { Inter, Roboto_Mono } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 폰트 옵션 적용
// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'swap',
// })

export const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto_mono.className}
      >
        <header className="w-full h-[60px]">
        
        {/* 로고 사용 */}
        {/* <Image height={40} src={Logo} alt="logo"></Image> */}
        </header>
        {children}
      </body>
    </html>
  );
}
